In [114]:
import numpy as np
import pandas as pd

def numer_4(txt):
    txt = txt.replace(" ",",")
    txt = txt.replace("\n", "")
    txt = txt.replace(".","")
    
    import json
    txt = json.loads(txt)
    return txt

def numer_40(txt):
    txt = txt.replace("\n","")
    txt = txt.replace(" ",",")
    for i in range(2,10):
        txt = txt.replace(i*",","")
    txt = txt.replace(".,",",")
    
    import json
    txt = json.loads(txt)
    
    return txt

def numer_400(txt):    
    txt = txt.replace("\n","")
    txt = txt.replace(" ",",")
    for i in range(3,10):
        txt = txt.replace(i*",","")
    txt = txt[:-2] + "]"
    txt = txt.replace(".,",",")
    
    txt = json.loads(txt)
    return(txt)

def numer_4000(txt):
    txt = txt.replace(" ", ",").replace("\n","")
    for i in range(2,10):
        txt = txt.replace(i*",","")
    txt = txt.replace("0.0","0,0").replace(".0",",0").replace(".,]","]")
    txt = txt.replace(".,",",")
    
    
    import json
    txt = json.loads(txt)
    
    return(txt)

def numer_40000(t):
    t = t.replace(" ",",").replace("\n", "")

    for i in range(2,10):
        t = t.replace(i*",", ",")
    t = t.replace(".,,]","]") 
    t = t.replace(".,",",")

    import json
    t = json.loads(t)
    
    return t

df = pd.read_csv("df_env_infos.csv", index_col=[0])
for i in range(len(df["weights"])):
    try:
        df["weights"].loc[i] = numer(df["weights"].loc[i])
        print("1",i)
    except:
        try:
            df["weights"].loc[i] = numer_4(df["weights"].loc[i])
            print("2",i)
        except:
            try:
                df["weights"].loc[i] = numer_40(df["weights"].loc[i])
                print("3",i)
            except:
                try:
                    df["weights"].loc[i] = numer_400(df["weights"].loc[i])
                    print("4",i)
                except:
                    try:
                        df["weights"].loc[i] = numer_4000(df["weights"].loc[i])
                        print("5",i)
                    except:
                        try:
                            df["weights"].loc[i] = numer_40000(df["weights"].loc[i])
                            print("6",i)
                        except:
                            print(i)

3 0
3 1
3 2
3 3
3 4
3 5
6 6
6 7
6 8
6 9
6 10
6 11
6 12
6 13
3 14
3 15
3 16
3 17
3 18
3 19
3 20
3 21
3 22
3 23
3 24
6 25
6 26
3 27
3 28
6 29
6 30
6 31
6 32
3 33
3 34
3 35
3 36
3 37
3 38
3 39
3 40
3 41
3 42
3 43
3 44
3 45
3 46
3 47
6 48
6 49
3 50
3 51
3 52
3 53
3 54
3 55
3 56
3 57
3 58
3 59
3 60
3 61
3 62
3 63
3 64
3 65
3 66
3 67
3 68
3 69
3 70
3 71
3 72
3 73
3 74
3 75
3 76
3 77
3 78
6 79
6 80
6 81
6 82
6 83
6 84
6 85
6 86
6 87
3 88
3 89
3 90
3 91
3 92
3 93
3 94
3 95
3 96
3 97
3 98
3 99
3 100
3 101
3 102
3 103
3 104
3 105
3 106
3 107
3 108
3 109
3 110
3 111
3 112
3 113
3 114
3 115
3 116
3 117
3 118
3 119
3 120
3 121
3 122
3 123
3 124
3 125
3 126
3 127
3 128
3 129
3 130
3 131
3 132
133
134
135
136
137
138
139
140

In [115]:
All_weights =  df["weights"][:133]
stocks = pd.read_csv("Stocks_for_each_mkt.csv", index_col = [0])

In [116]:
stocks.head()

,DATAYM,Asia_Bond,Asia_Equity,Creat_China_Equity,EmgMkt_Bond,EmgMkt_Equity,Europe_Bond,Europe_Equity,Global_Bond,Global_Equity,HY_Bond,Multi_Asset,Other_Bond,Other_Equity,US_Bond,US_Equity
0,2005-03-01,-0.023086,-0.029822,-0.010022,-0.040838,-0.004553,0.007458,-0.024580,-0.079240,-0.024955,-0.039027,-0.009737,-0.011387,0.036852,-0.037037,-0.043791
1,2005-04-01,0.004975,0.003188,0.009191,-0.016958,0.038638,-0.000461,-0.016578,-0.023471,-0.056673,-0.003995,0.017217,0.007961,-0.013556,-0.047511,-0.041405
2,2005-05-01,-0.013614,0.015842,-0.001532,0.017595,0.031362,-0.029300,-0.005664,0.045157,0.098837,-0.004679,0.008270,-0.002686,0.033570,0.073634,0.009817
3,2005-06-01,0.030113,0.005848,-0.007063,0.012864,0.021636,0.028293,0.010443,0.012544,-0.004409,0.030222,0.008738,-0.008131,-0.008666,-0.015487,0.097861
4,2005-07-01,0.069428,0.001051,-0.010884,0.048014,-0.033824,0.007854,0.033154,0.071576,0.062887,0.024120,-0.010344,-0.011955,0.180639,0.058427,0.095632

In [117]:
long = stocks.iloc[:,1:]+1

In [118]:
short = -stocks.iloc[:,1:] +1

In [119]:
stocks = pd.concat([ stocks.iloc[:,0], long, short ], axis = 1)

In [120]:
M_v_weights = l

In [121]:
port_v = []
for i in range(133):
    t = [1]+list(stocks.iloc[7+i][1:].values)
    t = np.array(t)
    
    print(t.shape)
    w0 = All_weights[i]
    w0 = np.array(w0)
    
    
    t = np.asarray(t, dtype='float32')
    w0 = np.asarray(w0, dtype='float32')
    
    p = np.dot(w0,t)
    port_v.append(p)

M_v = []
for i in range(133):
    t = [1]+list(stocks.iloc[7+i][1:].values)
    t = np.array(t)
    w0 = M_v_weights
    w0 = np.array(w0)
    
    
    t = np.asarray(t, dtype='float32')
    w0 = np.asarray(w0, dtype='float32')
    
    p = np.dot(w0,t)
    M_v.append(p)

(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)
(31,)

NameError: name 'M_v_weights' is not defined

In [122]:
np.cumprod(port_v)

array([0.9395758 , 0.9429029 , 0.9768108 , 1.0863816 , 1.0072504 ,
       1.0555248 , 1.1110932 , 1.0767926 , 1.0738059 , 1.0694059 ,
       1.0357463 , 0.9790104 , 0.99579334, 1.0534202 , 1.0406911 ,
       1.0212071 , 1.0169878 , 1.0512589 , 1.0861472 , 1.1308978 ,
       1.1517156 , 1.1648128 , 1.1468146 , 1.2258713 , 1.2655134 ,
       1.2437744 , 1.2399924 , 1.3887675 , 1.2868361 , 1.3744422 ,
       1.2797982 , 1.2352344 , 1.3545759 , 1.4495881 , 1.5414144 ,
       1.8445576 , 2.34805   , 2.4418814 , 2.26435   , 2.4200876 ,
       2.6213026 , 2.2318826 , 2.409315  , 2.6498826 , 2.562324  ,
       2.5993676 , 2.6415563 , 2.7687254 , 2.8434474 , 2.863895  ,
       2.9462376 , 2.8625307 , 2.8305936 , 2.9541185 , 3.0058749 ,
       2.691184  , 2.5691288 , 2.7435496 , 2.648752  , 2.918276  ,
       3.0153842 , 3.113356  , 3.4079673 , 3.4971933 , 3.703409  ,
       3.7805207 , 3.728083  , 3.6587596 , 3.5199122 , 3.5438395 ,
       3.1966472 , 2.7150888 , 3.1735008 , 3.0922816 , 3.0067263 ,
       3.1590009 , 3.3078616 , 3.091761  , 3.0464294 , 2.702845  ,
       2.7796087 , 2.9068694 , 2.914404  , 2.9640036 , 2.882281  ,
       2.833281  , 2.8116841 , 3.0108593 , 2.9627426 , 3.0159564 ,
       2.969312  , 3.040882  , 2.9358077 , 3.0633447 , 3.0503943 ,
       3.0892215 , 3.1939664 , 3.1739101 , 3.2126164 , 3.0644748 ,
       3.2050815 , 3.2218535 , 3.3522234 , 3.3878453 , 3.5467474 ,
       3.4474924 , 3.436001  , 3.2521374 , 3.031424  , 2.841053  ,
       2.7876205 , 2.6765773 , 2.7722967 , 2.691097  , 2.914013  ,
       2.7548761 , 2.6446683 , 2.4404075 , 2.2346218 , 2.1324885 ,
       2.3424742 , 2.332762  , 2.088374  , 2.0199478 , 2.0136352 ,
       2.1958783 , 2.3568017 , 2.3149257 , 2.3389406 , 2.2851708 ,
       2.362763  , 2.4048243 , 2.3520586 ], dtype=float32)