In [419]:
import pandas as pd
import numpy as np

In [420]:
name_L = pd.read_csv("15_name_test_2017_01_01_random.txt")["Unnamed: 0"]

In [421]:
name_L

0     0P00015JMC
1     0P000027CH
2     0P00000T49
3     0P0000S1X8
4     0P00009TC2
5     0P00000DZ1
6     0P00000RVG
7     0P00016YSJ
8     0P00011V6D
9     0P00000FLY
10    0P00016EOM
11    0P00016YR0
12    0P000099YB
13    0P00000AQE
14    0P00000SGC
Name: Unnamed: 0, dtype: object

In [422]:
data_df = pd.read_csv("data/Monthly_Fund_Return_Test.csv")

In [423]:
data_df.head()

,PERFORMANCEID,DATAYM,RET1M,ISINCODE,MSCategory,RISKTYPENAME,PRDTYPENAME,ISSUECRYID,ASSETNAME,GLOBALCNAME,MSCATEGORYNAME,BNPNAME,FX.RET1M
0,0P00000AMR,2017-01-01,0.052065,LU0028119013,163.0,Equity,MUTUAL FUND,EUR,Equity,Europe Equity Mid/Small Cap,Europe Small-Cap Equity,Europe Equity,0.021224
1,0P00000AMS,2017-01-01,0.014790,LU0028118809,159.0,Equity,MUTUAL FUND,EUR,Equity,Europe Equity Large Cap,Europe Large-Cap Blend Equity,Europe Equity,0.021224
2,0P00000AMT,2017-01-01,0.015403,LU0100598282,159.0,Equity,MUTUAL FUND,EUR,Equity,Europe Equity Large Cap,Europe Large-Cap Blend Equity,Europe Equity,0.021224
3,0P00000AMU,2017-01-01,0.045300,LU0052864419,182.0,Equity,MUTUAL FUND,USD,Equity,Consumer Goods&amp;Services Sector Equity,Sector Equity Consumer Goods & Services,Other Equity,0.000000
4,0P00000AMY,2017-01-01,0.059300,LU0048816135,148.0,Equity,MUTUAL FUND,USD,Equity,Greater China Equity,Greater China Equity,Creat China Equity,0.000000

In [424]:
# data_df[data_df["PERFORMANCEID"]=="0P00019VT4"]

In [425]:
date = pd.DataFrame(data_df[data_df["PERFORMANCEID"] == "0P00015JMD"]["DATAYM"].reset_index()["DATAYM"])

for i in range(len(name_L)):
    tmp = data_df[data_df["PERFORMANCEID"] == name_L[i]]["RET1M"].reset_index()["RET1M"]
    tmp = pd.DataFrame(tmp).rename(columns = {"RET1M":name_L[i]})
    
    date = pd.concat([date,tmp], axis = 1)

In [426]:
date

,DATAYM,0P00015JMC,0P000027CH,0P00000T49,0P0000S1X8,0P00009TC2,0P00000DZ1,0P00000RVG,0P00016YSJ,0P00011V6D,0P00000FLY,0P00016EOM,0P00016YR0,0P000099YB,0P00000AQE,0P00000SGC
0,2017-01-01,0.040946,0.036400,0.079900,0.015300,0.069483,0.017343,0.052371,0.001500,0.014289,0.011700,0.021000,0.030908,0.030600,0.008500,0.091410
1,2017-02-01,0.045761,0.012600,0.029500,0.018900,0.036394,0.003517,0.006973,0.009800,0.032701,0.014900,0.027200,0.017523,0.045882,0.008600,0.030234
2,2017-03-01,-0.035966,0.005800,0.009000,0.005700,0.020456,0.008456,0.011887,0.006500,0.012633,-0.002000,0.009600,0.000027,0.023851,-0.000100,0.030501
3,2017-04-01,0.020117,0.013500,0.016600,0.011900,0.003282,0.024860,0.069866,0.008400,-0.011491,0.011200,0.014300,0.003928,-0.008784,0.007100,0.036760
4,2017-05-01,0.023334,0.064000,0.042700,0.008300,0.008268,0.036305,0.025517,0.012000,0.015363,0.004500,0.016500,0.022890,0.009243,0.007300,0.059586
5,2017-06-01,0.008598,0.005200,0.012800,0.003500,0.019587,0.018167,0.001334,0.003100,0.011152,-0.000600,-0.008000,-0.000274,0.029281,0.001200,-0.001881
6,2017-07-01,0.011036,0.033400,0.073100,0.010900,0.050224,0.035226,0.038617,0.009000,0.004000,0.009300,0.024500,0.014434,0.027587,0.004300,0.033997
7,2017-08-01,0.016166,0.014600,0.019200,0.011400,0.024705,0.020431,0.001871,0.005000,0.008244,0.002700,0.013900,0.019096,0.022235,0.007500,0.024788
8,2017-09-01,-0.031432,0.013700,-0.005300,0.006200,-0.018171,-0.007646,0.052157,-0.007000,0.009057,0.007700,0.006100,-0.008238,-0.024672,-0.001000,-0.018838
9,2017-10-01,-0.032582,0.063700,0.029900,0.008000,0.036028,-0.002156,0.005545,-0.004800,0.009547,0.002700,0.013600,0.007828,0.020668,-0.001600,0.027167
10,2017-11-01,0.029833,0.028200,0.014600,0.004300,-0.009022,0.018488,-0.009124,0.009500,0.022804,-0.003900,0.005900,0.002894,0.026387,-0.001100,0.042399
11,2017-12-01,0.102049,0.022500,0.028200,0.000700,0.024838,0.007116,0.028876,-0.002400,0.006987,-0.000600,0.008500,0.017279,0.030580,0.002500,0.011961
12,2018-01-01,0.036337,0.066800,0.133600,0.004200,0.093840,0.042481,0.063412,0.012800,0.046483,0.002500,0.050100,0.037738,0.065271,-0.005900,0.101200
13,2018-02-01,0.022277,-0.026800,-0.065200,-0.008200,-0.034868,-0.014073,-0.027353,-0.010700,-0.031084,-0.010700,-0.027600,-0.015432,-0.012694,-0.011500,0.027078
14,2018-03-01,-0.021195,-0.015000,-0.034300,-0.005000,-0.017653,-0.001454,-0.037915,0.009900,-0.022867,-0.008900,-0.010700,0.012949,-0.000997,0.002800,-0.054139
15,2018-04-01,-0.050390,-0.004000,-0.017800,-0.003500,-0.010956,-0.015180,0.011963,-0.015400,-0.005968,0.002700,-0.024200,-0.019097,0.012043,-0.008100,0.033082
16,2018-05-01,-0.010316,0.005700,0.049200,-0.010900,-0.052199,-0.041417,-0.007013,-0.025300,0.006082,-0.007500,-0.015400,-0.033542,-0.006953,0.003800,0.063594
17,2018-06-01,-0.105739,-0.037300,-0.054200,-0.010500,-0.067503,-0.009897,-0.028853,-0.001100,-0.007289,-0.002300,-0.017900,-0.052909,-0.006602,-0.004500,0.009611
18,2018-07-01,0.052789,-0.016600,-0.025100,0.020700,0.044673,0.015375,0.013359,0.007800,0.044827,0.011500,0.005700,-0.005684,0.016108,0.003200,-0.012580
19,2018-08-01,-0.108558,-0.003600,-0.025700,-0.016000,-0.037426,-0.004627,-0.015896,-0.006900,0.006483,0.001200,-0.001600,-0.023329,0.025641,0.001300,0.098795
20,2018-09-01,0.039016,0.021300,0.000400,0.013900,-0.008941,-0.006374,0.006058,-0.000100,0.002729,0.004700,0.000500,0.002626,0.031481,-0.001800,-0.007644
21,2018-10-01,-0.046209,-0.101800,-0.112300,-0.002900,-0.076797,-0.028783,-0.106324,-0.023000,-0.067029,-0.014200,-0.044800,-0.027368,-0.092370,-0.007500,-0.108748
22,2018-11-01,0.069558,-0.001428,0.050240,-0.006488,0.022402,-0.007377,-0.012718,0.001767,0.025761,-0.010875,0.001001,-0.001119,0.010867,0.002437,0.004874
23,2018-12-01,-0.040523,-0.077116,-0.047037,0.007457,-0.041448,0.006274,-0.071680,0.017162,-0.067526,-0.014531,-0.039301,0.009917,-0.019980,0.010120,-0.079638
24,2019-01-01,0.111360,0.071934,0.101470,0.027085,0.115361,0.019100,0.065584,0.014131,0.054351,0.040460,0.042938,0.055678,0.016142,0.017492,0.122905
25,2019-02-01,-0.028440,0.011912,0.037432,0.017615,-0.000980,-0.001965,0.001309,-0.001266,0.033428,0.014885,0.010688,0.012403,0.026276,0.000535,0.043546
26,2019-03-01,-0.027576,0.006791,0.003787,0.009972,0.022527,0.002075,0.003510,0.007335,0.011666,0.007888,0.003891,0.000311,0.011130,0.014924,0.010233
27,2019-04-01,0.025256,0.012716,0.019524,0.010510,-0.005144,0.006133,0.041062,0.001278,0.006727,0.011234,0.000547,0.002800,0.020281,0.001715,0.043832
28,2019-05-01,-0.020763,-0.041499,-0.099008,0.005796,-0.054213,-0.004831,-0.059018,0.010002,-0.024457,-0.008864,-0.028805,-0.026974,-0.022329,0.015682,-0.036901
29,2019-06-01,0.060532,0.035018,0.071459,0.021215,0.070925,0.042170,0.030712,0.023140,0.058813,0.023338,0.030355,0.032583,0.039874,0.014025,0.060103

In [427]:

date.to_csv("test_Stock_for_each_mkt.csv")